all:
    echo left or right or push

left:
    make -C ../../../.. ferris/sweep:pistahh-cdh-hu2:dfu-split-left

right:
    make -C ../../../.. ferris/sweep:pistahh-cdh-hu2:dfu-split-right

push:
    git add -A . && git commit -m "Updates" && git push
